# Generated by Django 3.0.6 on 2020-06-03 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
